on: [push]
name: build
jobs:
  runhaskell:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4"
          cabal-version: "3.10.3.0"
      - run: cabal build all
